-- Migration: V21__pays_noms_francais.sql
-- Corrige les noms de pays en français (CLDR via babel) : la table pays contenait des
-- noms en anglais (issus de restcountries.com, qui utilisait name.common sans traduction).
-- restcountries.com v3.1 est désormais dépréciée (v5 nécessite une clé API payante),
-- donc on fige une bonne source de référence statique (CLDR) plutôt que de dépendre
-- d'un service externe pour ces données stables.

BEGIN;

UPDATE pays SET nom = 'Andorre' WHERE code_iso = 'AD';
UPDATE pays SET nom = 'Émirats arabes unis' WHERE code_iso = 'AE';
UPDATE pays SET nom = 'Afghanistan' WHERE code_iso = 'AF';
UPDATE pays SET nom = 'Antigua-et-Barbuda' WHERE code_iso = 'AG';
UPDATE pays SET nom = 'Anguilla' WHERE code_iso = 'AI';
UPDATE pays SET nom = 'Albanie' WHERE code_iso = 'AL';
UPDATE pays SET nom = 'Arménie' WHERE code_iso = 'AM';
UPDATE pays SET nom = 'Angola' WHERE code_iso = 'AO';
UPDATE pays SET nom = 'Antarctique' WHERE code_iso = 'AQ';
UPDATE pays SET nom = 'Argentine' WHERE code_iso = 'AR';
UPDATE pays SET nom = 'Samoa américaines' WHERE code_iso = 'AS';
UPDATE pays SET nom = 'Autriche' WHERE code_iso = 'AT';
UPDATE pays SET nom = 'Australie' WHERE code_iso = 'AU';
UPDATE pays SET nom = 'Aruba' WHERE code_iso = 'AW';
UPDATE pays SET nom = 'Îles Åland' WHERE code_iso = 'AX';
UPDATE pays SET nom = 'Azerbaïdjan' WHERE code_iso = 'AZ';
UPDATE pays SET nom = 'Bosnie-Herzégovine' WHERE code_iso = 'BA';
UPDATE pays SET nom = 'Barbade' WHERE code_iso = 'BB';
UPDATE pays SET nom = 'Bangladesh' WHERE code_iso = 'BD';
UPDATE pays SET nom = 'Belgique' WHERE code_iso = 'BE';
UPDATE pays SET nom = 'Burkina Faso' WHERE code_iso = 'BF';
UPDATE pays SET nom = 'Bulgarie' WHERE code_iso = 'BG';
UPDATE pays SET nom = 'Bahreïn' WHERE code_iso = 'BH';
UPDATE pays SET nom = 'Burundi' WHERE code_iso = 'BI';
UPDATE pays SET nom = 'Bénin' WHERE code_iso = 'BJ';
UPDATE pays SET nom = 'Saint-Barthélemy' WHERE code_iso = 'BL';
UPDATE pays SET nom = 'Bermudes' WHERE code_iso = 'BM';
UPDATE pays SET nom = 'Brunei' WHERE code_iso = 'BN';
UPDATE pays SET nom = 'Bolivie' WHERE code_iso = 'BO';
UPDATE pays SET nom = 'Pays-Bas caribéens' WHERE code_iso = 'BQ';
UPDATE pays SET nom = 'Brésil' WHERE code_iso = 'BR';
UPDATE pays SET nom = 'Bahamas' WHERE code_iso = 'BS';
UPDATE pays SET nom = 'Bhoutan' WHERE code_iso = 'BT';
UPDATE pays SET nom = 'Île Bouvet' WHERE code_iso = 'BV';
UPDATE pays SET nom = 'Botswana' WHERE code_iso = 'BW';
UPDATE pays SET nom = 'Biélorussie' WHERE code_iso = 'BY';
UPDATE pays SET nom = 'Belize' WHERE code_iso = 'BZ';
UPDATE pays SET nom = 'Canada' WHERE code_iso = 'CA';
UPDATE pays SET nom = 'Îles Cocos' WHERE code_iso = 'CC';
UPDATE pays SET nom = 'Congo-Kinshasa' WHERE code_iso = 'CD';
UPDATE pays SET nom = 'République centrafricaine' WHERE code_iso = 'CF';
UPDATE pays SET nom = 'Congo-Brazzaville' WHERE code_iso = 'CG';
UPDATE pays SET nom = 'Suisse' WHERE code_iso = 'CH';
UPDATE pays SET nom = 'Côte d’Ivoire' WHERE code_iso = 'CI';
UPDATE pays SET nom = 'Îles Cook' WHERE code_iso = 'CK';
UPDATE pays SET nom = 'Chili' WHERE code_iso = 'CL';
UPDATE pays SET nom = 'Cameroun' WHERE code_iso = 'CM';
UPDATE pays SET nom = 'Chine' WHERE code_iso = 'CN';
UPDATE pays SET nom = 'Colombie' WHERE code_iso = 'CO';
UPDATE pays SET nom = 'Costa Rica' WHERE code_iso = 'CR';
UPDATE pays SET nom = 'Cuba' WHERE code_iso = 'CU';
UPDATE pays SET nom = 'Cap-Vert' WHERE code_iso = 'CV';
UPDATE pays SET nom = 'Curaçao' WHERE code_iso = 'CW';
UPDATE pays SET nom = 'Île Christmas' WHERE code_iso = 'CX';
UPDATE pays SET nom = 'Chypre' WHERE code_iso = 'CY';
UPDATE pays SET nom = 'Tchéquie' WHERE code_iso = 'CZ';
UPDATE pays SET nom = 'Allemagne' WHERE code_iso = 'DE';
UPDATE pays SET nom = 'Djibouti' WHERE code_iso = 'DJ';
UPDATE pays SET nom = 'Danemark' WHERE code_iso = 'DK';
UPDATE pays SET nom = 'Dominique' WHERE code_iso = 'DM';
UPDATE pays SET nom = 'République dominicaine' WHERE code_iso = 'DO';
UPDATE pays SET nom = 'Algérie' WHERE code_iso = 'DZ';
UPDATE pays SET nom = 'Équateur' WHERE code_iso = 'EC';
UPDATE pays SET nom = 'Estonie' WHERE code_iso = 'EE';
UPDATE pays SET nom = 'Égypte' WHERE code_iso = 'EG';
UPDATE pays SET nom = 'Sahara occidental' WHERE code_iso = 'EH';
UPDATE pays SET nom = 'Érythrée' WHERE code_iso = 'ER';
UPDATE pays SET nom = 'Espagne' WHERE code_iso = 'ES';
UPDATE pays SET nom = 'Éthiopie' WHERE code_iso = 'ET';
UPDATE pays SET nom = 'Finlande' WHERE code_iso = 'FI';
UPDATE pays SET nom = 'Fidji' WHERE code_iso = 'FJ';
UPDATE pays SET nom = 'Îles Malouines' WHERE code_iso = 'FK';
UPDATE pays SET nom = 'Micronésie' WHERE code_iso = 'FM';
UPDATE pays SET nom = 'Îles Féroé' WHERE code_iso = 'FO';
UPDATE pays SET nom = 'France' WHERE code_iso = 'FR';
UPDATE pays SET nom = 'Gabon' WHERE code_iso = 'GA';
UPDATE pays SET nom = 'Royaume-Uni' WHERE code_iso = 'GB';
UPDATE pays SET nom = 'Grenade' WHERE code_iso = 'GD';
UPDATE pays SET nom = 'Géorgie' WHERE code_iso = 'GE';
UPDATE pays SET nom = 'Guyane française' WHERE code_iso = 'GF';
UPDATE pays SET nom = 'Guernesey' WHERE code_iso = 'GG';
UPDATE pays SET nom = 'Ghana' WHERE code_iso = 'GH';
UPDATE pays SET nom = 'Gibraltar' WHERE code_iso = 'GI';
UPDATE pays SET nom = 'Groenland' WHERE code_iso = 'GL';
UPDATE pays SET nom = 'Gambie' WHERE code_iso = 'GM';
UPDATE pays SET nom = 'Guinée' WHERE code_iso = 'GN';
UPDATE pays SET nom = 'Guadeloupe' WHERE code_iso = 'GP';
UPDATE pays SET nom = 'Guinée équatoriale' WHERE code_iso = 'GQ';
UPDATE pays SET nom = 'Grèce' WHERE code_iso = 'GR';
UPDATE pays SET nom = 'Géorgie du Sud-et-les Îles Sandwich du Sud' WHERE code_iso = 'GS';
UPDATE pays SET nom = 'Guatemala' WHERE code_iso = 'GT';
UPDATE pays SET nom = 'Guam' WHERE code_iso = 'GU';
UPDATE pays SET nom = 'Guinée-Bissau' WHERE code_iso = 'GW';
UPDATE pays SET nom = 'Guyana' WHERE code_iso = 'GY';
UPDATE pays SET nom = 'R.A.S. chinoise de Hong Kong' WHERE code_iso = 'HK';
UPDATE pays SET nom = 'Îles Heard-et-MacDonald' WHERE code_iso = 'HM';
UPDATE pays SET nom = 'Honduras' WHERE code_iso = 'HN';
UPDATE pays SET nom = 'Croatie' WHERE code_iso = 'HR';
UPDATE pays SET nom = 'Haïti' WHERE code_iso = 'HT';
UPDATE pays SET nom = 'Hongrie' WHERE code_iso = 'HU';
UPDATE pays SET nom = 'Indonésie' WHERE code_iso = 'ID';
UPDATE pays SET nom = 'Irlande' WHERE code_iso = 'IE';
UPDATE pays SET nom = 'Israël' WHERE code_iso = 'IL';
UPDATE pays SET nom = 'Île de Man' WHERE code_iso = 'IM';
UPDATE pays SET nom = 'Inde' WHERE code_iso = 'IN';
UPDATE pays SET nom = 'Territoire britannique de l’océan Indien' WHERE code_iso = 'IO';
UPDATE pays SET nom = 'Irak' WHERE code_iso = 'IQ';
UPDATE pays SET nom = 'Iran' WHERE code_iso = 'IR';
UPDATE pays SET nom = 'Islande' WHERE code_iso = 'IS';
UPDATE pays SET nom = 'Italie' WHERE code_iso = 'IT';
UPDATE pays SET nom = 'Jersey' WHERE code_iso = 'JE';
UPDATE pays SET nom = 'Jamaïque' WHERE code_iso = 'JM';
UPDATE pays SET nom = 'Jordanie' WHERE code_iso = 'JO';
UPDATE pays SET nom = 'Japon' WHERE code_iso = 'JP';
UPDATE pays SET nom = 'Kenya' WHERE code_iso = 'KE';
UPDATE pays SET nom = 'Kirghizstan' WHERE code_iso = 'KG';
UPDATE pays SET nom = 'Cambodge' WHERE code_iso = 'KH';
UPDATE pays SET nom = 'Kiribati' WHERE code_iso = 'KI';
UPDATE pays SET nom = 'Comores' WHERE code_iso = 'KM';
UPDATE pays SET nom = 'Saint-Christophe-et-Niévès' WHERE code_iso = 'KN';
UPDATE pays SET nom = 'Corée du Nord' WHERE code_iso = 'KP';
UPDATE pays SET nom = 'Corée du Sud' WHERE code_iso = 'KR';
UPDATE pays SET nom = 'Koweït' WHERE code_iso = 'KW';
UPDATE pays SET nom = 'Îles Caïmans' WHERE code_iso = 'KY';
UPDATE pays SET nom = 'Kazakhstan' WHERE code_iso = 'KZ';
UPDATE pays SET nom = 'Laos' WHERE code_iso = 'LA';
UPDATE pays SET nom = 'Liban' WHERE code_iso = 'LB';
UPDATE pays SET nom = 'Sainte-Lucie' WHERE code_iso = 'LC';
UPDATE pays SET nom = 'Liechtenstein' WHERE code_iso = 'LI';
UPDATE pays SET nom = 'Sri Lanka' WHERE code_iso = 'LK';
UPDATE pays SET nom = 'Liberia' WHERE code_iso = 'LR';
UPDATE pays SET nom = 'Lesotho' WHERE code_iso = 'LS';
UPDATE pays SET nom = 'Lituanie' WHERE code_iso = 'LT';
UPDATE pays SET nom = 'Luxembourg' WHERE code_iso = 'LU';
UPDATE pays SET nom = 'Lettonie' WHERE code_iso = 'LV';
UPDATE pays SET nom = 'Libye' WHERE code_iso = 'LY';
UPDATE pays SET nom = 'Maroc' WHERE code_iso = 'MA';
UPDATE pays SET nom = 'Monaco' WHERE code_iso = 'MC';
UPDATE pays SET nom = 'Moldavie' WHERE code_iso = 'MD';
UPDATE pays SET nom = 'Monténégro' WHERE code_iso = 'ME';
UPDATE pays SET nom = 'Saint-Martin' WHERE code_iso = 'MF';
UPDATE pays SET nom = 'Madagascar' WHERE code_iso = 'MG';
UPDATE pays SET nom = 'Îles Marshall' WHERE code_iso = 'MH';
UPDATE pays SET nom = 'Macédoine du Nord' WHERE code_iso = 'MK';
UPDATE pays SET nom = 'Mali' WHERE code_iso = 'ML';
UPDATE pays SET nom = 'Myanmar (Birmanie)' WHERE code_iso = 'MM';
UPDATE pays SET nom = 'Mongolie' WHERE code_iso = 'MN';
UPDATE pays SET nom = 'R.A.S. chinoise de Macao' WHERE code_iso = 'MO';
UPDATE pays SET nom = 'Îles Mariannes du Nord' WHERE code_iso = 'MP';
UPDATE pays SET nom = 'Martinique' WHERE code_iso = 'MQ';
UPDATE pays SET nom = 'Mauritanie' WHERE code_iso = 'MR';
UPDATE pays SET nom = 'Montserrat' WHERE code_iso = 'MS';
UPDATE pays SET nom = 'Malte' WHERE code_iso = 'MT';
UPDATE pays SET nom = 'Maurice' WHERE code_iso = 'MU';
UPDATE pays SET nom = 'Maldives' WHERE code_iso = 'MV';
UPDATE pays SET nom = 'Malawi' WHERE code_iso = 'MW';
UPDATE pays SET nom = 'Mexique' WHERE code_iso = 'MX';
UPDATE pays SET nom = 'Malaisie' WHERE code_iso = 'MY';
UPDATE pays SET nom = 'Mozambique' WHERE code_iso = 'MZ';
UPDATE pays SET nom = 'Namibie' WHERE code_iso = 'NA';
UPDATE pays SET nom = 'Nouvelle-Calédonie' WHERE code_iso = 'NC';
UPDATE pays SET nom = 'Niger' WHERE code_iso = 'NE';
UPDATE pays SET nom = 'Île Norfolk' WHERE code_iso = 'NF';
UPDATE pays SET nom = 'Nigeria' WHERE code_iso = 'NG';
UPDATE pays SET nom = 'Nicaragua' WHERE code_iso = 'NI';
UPDATE pays SET nom = 'Pays-Bas' WHERE code_iso = 'NL';
UPDATE pays SET nom = 'Norvège' WHERE code_iso = 'NO';
UPDATE pays SET nom = 'Népal' WHERE code_iso = 'NP';
UPDATE pays SET nom = 'Nauru' WHERE code_iso = 'NR';
UPDATE pays SET nom = 'Niue' WHERE code_iso = 'NU';
UPDATE pays SET nom = 'Nouvelle-Zélande' WHERE code_iso = 'NZ';
UPDATE pays SET nom = 'Oman' WHERE code_iso = 'OM';
UPDATE pays SET nom = 'Panama' WHERE code_iso = 'PA';
UPDATE pays SET nom = 'Pérou' WHERE code_iso = 'PE';
UPDATE pays SET nom = 'Polynésie française' WHERE code_iso = 'PF';
UPDATE pays SET nom = 'Papouasie-Nouvelle-Guinée' WHERE code_iso = 'PG';
UPDATE pays SET nom = 'Philippines' WHERE code_iso = 'PH';
UPDATE pays SET nom = 'Pakistan' WHERE code_iso = 'PK';
UPDATE pays SET nom = 'Pologne' WHERE code_iso = 'PL';
UPDATE pays SET nom = 'Saint-Pierre-et-Miquelon' WHERE code_iso = 'PM';
UPDATE pays SET nom = 'Îles Pitcairn' WHERE code_iso = 'PN';
UPDATE pays SET nom = 'Porto Rico' WHERE code_iso = 'PR';
UPDATE pays SET nom = 'Territoires palestiniens' WHERE code_iso = 'PS';
UPDATE pays SET nom = 'Portugal' WHERE code_iso = 'PT';
UPDATE pays SET nom = 'Palaos' WHERE code_iso = 'PW';
UPDATE pays SET nom = 'Paraguay' WHERE code_iso = 'PY';
UPDATE pays SET nom = 'Qatar' WHERE code_iso = 'QA';
UPDATE pays SET nom = 'La Réunion' WHERE code_iso = 'RE';
UPDATE pays SET nom = 'Roumanie' WHERE code_iso = 'RO';
UPDATE pays SET nom = 'Serbie' WHERE code_iso = 'RS';
UPDATE pays SET nom = 'Russie' WHERE code_iso = 'RU';
UPDATE pays SET nom = 'Rwanda' WHERE code_iso = 'RW';
UPDATE pays SET nom = 'Arabie saoudite' WHERE code_iso = 'SA';
UPDATE pays SET nom = 'Îles Salomon' WHERE code_iso = 'SB';
UPDATE pays SET nom = 'Seychelles' WHERE code_iso = 'SC';
UPDATE pays SET nom = 'Soudan' WHERE code_iso = 'SD';
UPDATE pays SET nom = 'Suède' WHERE code_iso = 'SE';
UPDATE pays SET nom = 'Singapour' WHERE code_iso = 'SG';
UPDATE pays SET nom = 'Sainte-Hélène' WHERE code_iso = 'SH';
UPDATE pays SET nom = 'Slovénie' WHERE code_iso = 'SI';
UPDATE pays SET nom = 'Svalbard et Jan Mayen' WHERE code_iso = 'SJ';
UPDATE pays SET nom = 'Slovaquie' WHERE code_iso = 'SK';
UPDATE pays SET nom = 'Sierra Leone' WHERE code_iso = 'SL';
UPDATE pays SET nom = 'Saint-Marin' WHERE code_iso = 'SM';
UPDATE pays SET nom = 'Sénégal' WHERE code_iso = 'SN';
UPDATE pays SET nom = 'Somalie' WHERE code_iso = 'SO';
UPDATE pays SET nom = 'Suriname' WHERE code_iso = 'SR';
UPDATE pays SET nom = 'Soudan du Sud' WHERE code_iso = 'SS';
UPDATE pays SET nom = 'Sao Tomé-et-Principe' WHERE code_iso = 'ST';
UPDATE pays SET nom = 'Salvador' WHERE code_iso = 'SV';
UPDATE pays SET nom = 'Saint-Martin (partie néerlandaise)' WHERE code_iso = 'SX';
UPDATE pays SET nom = 'Syrie' WHERE code_iso = 'SY';
UPDATE pays SET nom = 'Eswatini' WHERE code_iso = 'SZ';
UPDATE pays SET nom = 'Îles Turques-et-Caïques' WHERE code_iso = 'TC';
UPDATE pays SET nom = 'Tchad' WHERE code_iso = 'TD';
UPDATE pays SET nom = 'Terres australes françaises' WHERE code_iso = 'TF';
UPDATE pays SET nom = 'Togo' WHERE code_iso = 'TG';
UPDATE pays SET nom = 'Thaïlande' WHERE code_iso = 'TH';
UPDATE pays SET nom = 'Tadjikistan' WHERE code_iso = 'TJ';
UPDATE pays SET nom = 'Tokelau' WHERE code_iso = 'TK';
UPDATE pays SET nom = 'Timor oriental' WHERE code_iso = 'TL';
UPDATE pays SET nom = 'Turkménistan' WHERE code_iso = 'TM';
UPDATE pays SET nom = 'Tunisie' WHERE code_iso = 'TN';
UPDATE pays SET nom = 'Tonga' WHERE code_iso = 'TO';
UPDATE pays SET nom = 'Turquie' WHERE code_iso = 'TR';
UPDATE pays SET nom = 'Trinité-et-Tobago' WHERE code_iso = 'TT';
UPDATE pays SET nom = 'Tuvalu' WHERE code_iso = 'TV';
UPDATE pays SET nom = 'Taïwan' WHERE code_iso = 'TW';
UPDATE pays SET nom = 'Tanzanie' WHERE code_iso = 'TZ';
UPDATE pays SET nom = 'Ukraine' WHERE code_iso = 'UA';
UPDATE pays SET nom = 'Ouganda' WHERE code_iso = 'UG';
UPDATE pays SET nom = 'Îles mineures éloignées des États-Unis' WHERE code_iso = 'UM';
UPDATE pays SET nom = 'États-Unis' WHERE code_iso = 'US';
UPDATE pays SET nom = 'Uruguay' WHERE code_iso = 'UY';
UPDATE pays SET nom = 'Ouzbékistan' WHERE code_iso = 'UZ';
UPDATE pays SET nom = 'État de la Cité du Vatican' WHERE code_iso = 'VA';
UPDATE pays SET nom = 'Saint-Vincent-et-les Grenadines' WHERE code_iso = 'VC';
UPDATE pays SET nom = 'Venezuela' WHERE code_iso = 'VE';
UPDATE pays SET nom = 'Îles Vierges britanniques' WHERE code_iso = 'VG';
UPDATE pays SET nom = 'Îles Vierges des États-Unis' WHERE code_iso = 'VI';
UPDATE pays SET nom = 'Viêt Nam' WHERE code_iso = 'VN';
UPDATE pays SET nom = 'Vanuatu' WHERE code_iso = 'VU';
UPDATE pays SET nom = 'Wallis-et-Futuna' WHERE code_iso = 'WF';
UPDATE pays SET nom = 'Samoa' WHERE code_iso = 'WS';
UPDATE pays SET nom = 'Kosovo' WHERE code_iso = 'XK';
UPDATE pays SET nom = 'Yémen' WHERE code_iso = 'YE';
UPDATE pays SET nom = 'Mayotte' WHERE code_iso = 'YT';
UPDATE pays SET nom = 'Afrique du Sud' WHERE code_iso = 'ZA';
UPDATE pays SET nom = 'Zambie' WHERE code_iso = 'ZM';
UPDATE pays SET nom = 'Zimbabwe' WHERE code_iso = 'ZW';

COMMIT;
