spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/smboutique_local
    username: smboutique_local_user
    password: local_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Frontend base for local dev
app:
  frontend:
    base-url: http://localhost:5173
