spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smboutique_local
    username: smboutique_local_user
    password: local_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
